name: CI Workflow

on:
  pull_request:
    branches:
      - main
      
jobs:
  linter:
    name: Проверка качества кода
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
       - name: Checkout repository
         uses: actions/checkout@v4.1.2
       - name: Установка Python
         uses: actions/setup-python@v5.0.0
         with:
           python-version: ${{ matrix.python-version }}
       - name:  Установка зависимостей
         run: |
           python -m pip install --upgrade pip
           pip install flake8 flake8-html wemake-python-styleguide==0.15.3 flake8-bandit bandit
       - name:  Установка зависимостей
         run: flake8 --format=html --htmldir=flake-report
          
           
       
    
