name: Workflow CI

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Проверка качества кода
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Установка Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8 wemake-python-styleguide flake8-html flake8-bandit bandit
      - name: Прогон через wemake-python-styleguide
        run: flake8 . --format=html --htmldir=flake-report
      - name: Визуализация результата
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: reports
           path: flake-report/*.html
           retention-days: 5
      
